### ISSUE TITLE
Merging nvim-llama with llm.nivm

### ISSUE THREAD

**Issue by JoseConseco** [jpmcb/nvim-llama#1]
Hi, I wanted to let you know that https://github.com/gsuuon/llm.nvim just got support for llamacpp (I made PR for it). 
Maybe it would be good idea, to merge and move your work into llm.nvim, rather that creating new plugin?  This way, way things could move faster. 
I made post on reddit about it : https://www.reddit.com/r/neovim/comments/16trc61/llamacpp_support_now_added_to_llmnvim/

And example configuration that uses llm.nvim
https://github.com/JoseConseco/nvim_config/blob/master/lua/nv_llm-nvim/init.lua

**Comment by jpmcb** [comment]
Hello! Thanks for the issue!

I'm actually hoping to transition this plugin to use ollama under the hood since it will abstract away much of the difficulty in building and maintain a c/c++ buildchain and library.

Look forward to that in the future and thanks for the headsup!
